[project]
name = "ore"

[[stacks]]
name = "ore"
stack = "OreStream"
url = "wss://ore.stack.usehyperstack.com"
typescript_output_file = "../sdk/typescript/src/ore/index.ts"
rust_output_crate = "../sdk/rust/src/ore"
rust_module = true
