[package]
name = "ore-rust-example"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
hyperstack-sdk = "0.5"
hyperstack-stacks = { version = "0.5", features = ["ore"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1"
